config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :month_calendar
  root to: 'calendars#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  def index
    @calendars = Calendar.all
  end

  def show
  end

  def new
    @calendar = Calendar.new
  end

  def edit
  end

    def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_calendar
    @calendar = Calendar.find(params[:id])
  end

  def calendar_params
    params.require(:calendar).permit(:event, :host, :activities, :address, :zipcode, :start_time, :end_time)
  end
end

app/controllers/month_calendar_controller.rb
class MonthCalendarController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/month_calendar_helper.rb
module MonthCalendarHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: calendar, local: true) do |form| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event %>
    <%= form.text_field :event, id: :calendar_event %>
  </div>

  <div class="field">
    <%= form.label :host %>
    <%= form.text_field :host, id: :calendar_host %>
  </div>

  <div class="field">
    <%= form.label :activities %>
    <%= form.text_field :activities, id: :calendar_activities %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :calendar_address %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.number_field :zipcode, id: :calendar_zipcode %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :calendar_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :calendar_end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calendars</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Host</th>
      <th>Activities</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.event %></td>
        <td><%= calendar.host %></td>
        <td><%= calendar.activities %></td>
        <td><%= calendar.address %></td>
        <td><%= calendar.zipcode %></td>
        <td><%= calendar.start_time %></td>
        <td><%= calendar.end_time %></td>
        <td><%= link_to 'Show', calendar %></td>
        <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
        <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calendar', new_calendar_path %>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @calendar.event %>
</p>

<p>
  <strong>Host:</strong>
  <%= @calendar.host %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @calendar.activities %>
</p>

<p>
  <strong>Address:</strong>
  <%= @calendar.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @calendar.zipcode %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @calendar.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @calendar.end_time %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCalender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= month_calendar(attribute: :start_date, end_attribute: :end_date) do |date| %>
        <%= date %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/month_calendar/index.html.erb
<%= month_calendar do |date| %>
  <%= date %>
<% end %>